### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by ARO-GZ** [QuTech-Delft/squidasm#3]
Hi, 
I followed the installation steps( `pip install netqasm` for the latest version and I installed squidasm from source). When I run `make verify`, all the requirements are successfully met, however, when trying to run the examples something fails. I get a `FileNotFoundError: [Errno 2] No such file or directory:` for the example `stack/link_layer_custom_subrt/example_ll_custom_subrt.py`.

Also, I do not know if everything should be covered here, but I guess it has something to do with the issues since when I tried running a simple piece of code I wrote it raised `WARNING: a expression handler missing`.
```
--------- coverage: platform linux, python 3.8.10-final-0 -----------
Name                                        Stmts   Miss  Cover
---------------------------------------------------------------
squidasm/__init__.py                            1      0   100%
squidasm/nqasm/__init__.py                      0      0   100%
squidasm/nqasm/executor/__init__.py             0      0   100%
squidasm/nqasm/executor/base.py               122     31    75%
squidasm/nqasm/executor/nv.py                  28     13    54%
squidasm/nqasm/executor/vanilla.py             13      0   100%
squidasm/nqasm/multithread.py                  57     11    81%
squidasm/nqasm/netstack.py                     77      3    96%
squidasm/nqasm/output.py                       41     15    63%
squidasm/nqasm/qnodeos.py                     167     10    94%
squidasm/nqasm/singlethread/__init__.py         0      0   100%
squidasm/nqasm/singlethread/connection.py      71     71     0%
squidasm/nqasm/singlethread/csocket.py         20     20     0%
squidasm/run/__init__.py                        0      0   100%
squidasm/run/multithread/__init__.py            0      0   100%
squidasm/run/multithread/runtime_mgr.py       163     10    94%
squidasm/run/multithread/simulate.py           61     46    25%
squidasm/run/singlethread/__init__.py           2      2     0%
squidasm/run/singlethread/context.py           43     43     0%
squidasm/run/singlethread/protocols.py        168    168     0%
squidasm/run/singlethread/run.py               72     72     0%
squidasm/run/singlethread/util.py              40     40     0%
squidasm/run/stack/__init__.py                  0      0   100%
squidasm/run/stack/build.py                    49     14    71%
squidasm/run/stack/config.py                  121     17    86%
squidasm/run/stack/run.py                      85     85     0%
squidasm/sim/__init__.py                        0      0   100%
squidasm/sim/glob.py                           98     34    65%
squidasm/sim/network/__init__.py                2      0   100%
squidasm/sim/network/network.py               243     56    77%
squidasm/sim/network/nv_config.py              72     34    53%
squidasm/sim/queues.py                         51      6    88%
squidasm/sim/stack/__init__.py                  0      0   100%
squidasm/sim/stack/common.py                  258     28    89%
squidasm/sim/stack/connection.py               51      6    88%
squidasm/sim/stack/context.py                  43      8    81%
squidasm/sim/stack/csocket.py                  30     10    67%
squidasm/sim/stack/egp.py                      69     14    80%
squidasm/sim/stack/globals.py                  40     21    48%
squidasm/sim/stack/handler.py                 166     12    93%
squidasm/sim/stack/host.py                     98      7    93%
squidasm/sim/stack/netstack.py                290     48    83%
squidasm/sim/stack/processor.py               505    144    71%
squidasm/sim/stack/program.py                  37      3    92%
squidasm/sim/stack/qnos.py                    118      5    96%
squidasm/sim/stack/sdk.py                      67     67     0%
squidasm/sim/stack/signals.py                   8      0   100%
squidasm/sim/stack/stack.py                   117      8    93%
squidasm/util/__init__.py                       0      0   100%
squidasm/util/ns.py                            43      3    93%
squidasm/util/sim.py                           28      5    82%
squidasm/util/thread.py                        15      2    87%
---------------------------------------------------------------
TOTAL                                        3850   1192    69%
```

I am on Ubuntu 20.04 and I tried creating conda environments with python version 3.7, 3.8 and 3.9. All lead to the same result. 
Thanks in advance for your time.

**Comment by bvdvecht** [comment]
Hi, thanks for trying out SquidASM!

Could you paste the full output when running `make verify`?
And just to make sure: are you on the latest commit of the `develop` branch? Does the file `examples/stack/link_layer_custom_subrt/example_ll_custom_subrt.py` exist in your local repository?

**Comment by ARO-GZ** [comment]
This is the output of `make verify`:
```
Requirement already satisfied: pytest in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from -r test_requirements.txt (line 1)) (6.2.5)
Requirement already satisfied: pytest-cov in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from -r test_requirements.txt (line 2)) (3.0.0)
Requirement already satisfied: flake8>=3.8.3 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from -r test_requirements.txt (line 3)) (4.0.1)
Requirement already satisfied: mypy>=0.812 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from -r test_requirements.txt (line 4)) (0.812)
Requirement already satisfied: black>=20.8b1 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from -r test_requirements.txt (line 5)) (21.12b0)
Requirement already satisfied: isort>=5.8.0 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from -r test_requirements.txt (line 6)) (5.10.1)
Requirement already satisfied: toml in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from pytest->-r test_requirements.txt (line 1)) (0.10.2)
Requirement already satisfied: pluggy<2.0,>=0.12 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from pytest->-r test_requirements.txt (line 1)) (1.0.0)
Requirement already satisfied: iniconfig in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from pytest->-r test_requirements.txt (line 1)) (1.1.1)
Requirement already satisfied: py>=1.8.2 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from pytest->-r test_requirements.txt (line 1)) (1.11.0)
Requirement already satisfied: packaging in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from pytest->-r test_requirements.txt (line 1)) (21.3)
Requirement already satisfied: attrs>=19.2.0 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from pytest->-r test_requirements.txt (line 1)) (21.4.0)
Requirement already satisfied: coverage[toml]>=5.2.1 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from pytest-cov->-r test_requirements.txt (line 2)) (6.2)
Requirement already satisfied: pycodestyle<2.9.0,>=2.8.0 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from flake8>=3.8.3->-r test_requirements.txt (line 3)) (2.8.0)
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from flake8>=3.8.3->-r test_requirements.txt (line 3)) (0.6.1)
Requirement already satisfied: pyflakes<2.5.0,>=2.4.0 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from flake8>=3.8.3->-r test_requirements.txt (line 3)) (2.4.0)
Requirement already satisfied: mypy-extensions<0.5.0,>=0.4.3 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from mypy>=0.812->-r test_requirements.txt (line 4)) (0.4.3)
Requirement already satisfied: typed-ast<1.5.0,>=1.4.0 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from mypy>=0.812->-r test_requirements.txt (line 4)) (1.4.3)
Requirement already satisfied: typing-extensions>=3.7.4 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from mypy>=0.812->-r test_requirements.txt (line 4)) (4.0.1)
Requirement already satisfied: pathspec<1,>=0.9.0 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from black>=20.8b1->-r test_requirements.txt (line 5)) (0.9.0)
Requirement already satisfied: platformdirs>=2 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from black>=20.8b1->-r test_requirements.txt (line 5)) (2.4.1)
Requirement already satisfied: click>=7.1.2 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from black>=20.8b1->-r test_requirements.txt (line 5)) (7.1.2)
Requirement already satisfied: tomli<2.0.0,>=0.2.6 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from black>=20.8b1->-r test_requirements.txt (line 5)) (1.2.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from packaging->pytest->-r test_requirements.txt (line 1)) (3.0.6)
Looking in indexes: https://pypi.org/simple, https://arodriguezoter:****@pypi.netsquid.org
Requirement already satisfied: click<8.0.0,>=7.1.1 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (7.1.2)
Requirement already satisfied: pydantic>=1.8.2 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (1.9.0)
Requirement already satisfied: netqasm>=0.7.0 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (0.8.6)
Requirement already satisfied: pydynaa<1.0,>=0.3 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (0.3.6)
Requirement already satisfied: netsquid<2.0.0,>=1.0.6 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (1.1.6)
Requirement already satisfied: netsquid-magic<13.0.0,>=12.1.0 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from -r requirements.txt (line 6)) (12.1.0)
Requirement already satisfied: netsquid-nv<9.0.0,>=8.0.0 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from -r requirements.txt (line 7)) (8.0.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from pydantic>=1.8.2->-r requirements.txt (line 2)) (4.0.1)
Requirement already satisfied: mypy==0.812 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from netqasm>=0.7.0->-r requirements.txt (line 3)) (0.812)
Requirement already satisfied: pytest-cov in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from netqasm>=0.7.0->-r requirements.txt (line 3)) (3.0.0)
Requirement already satisfied: pyyaml<6.0.0,>=5.3.1 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from netqasm>=0.7.0->-r requirements.txt (line 3)) (5.3.1)
Requirement already satisfied: pytest in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from netqasm>=0.7.0->-r requirements.txt (line 3)) (6.2.5)
Requirement already satisfied: qlink-interface<2.0.0,>=1.0.0 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from netqasm>=0.7.0->-r requirements.txt (line 3)) (1.0.0)
Requirement already satisfied: flake8>=3.8.3 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from netqasm>=0.7.0->-r requirements.txt (line 3)) (4.0.1)
Requirement already satisfied: numpy==1.18.0 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from netqasm>=0.7.0->-r requirements.txt (line 3)) (1.18.0)
Requirement already satisfied: requests>=2.25 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from netqasm>=0.7.0->-r requirements.txt (line 3)) (2.27.1)
Requirement already satisfied: black>=20.8b1 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from netqasm>=0.7.0->-r requirements.txt (line 3)) (21.12b0)
Requirement already satisfied: isort>=5.7.0 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from netqasm>=0.7.0->-r requirements.txt (line 3)) (5.10.1)
Requirement already satisfied: scipy<2.0.0,>=1.4.1 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from netqasm>=0.7.0->-r requirements.txt (line 3)) (1.7.3)
Requirement already satisfied: typed-ast<1.5.0,>=1.4.0 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from mypy==0.812->netqasm>=0.7.0->-r requirements.txt (line 3)) (1.4.3)
Requirement already satisfied: mypy-extensions<0.5.0,>=0.4.3 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from mypy==0.812->netqasm>=0.7.0->-r requirements.txt (line 3)) (0.4.3)
Requirement already satisfied: cysignals in /home/anton/.local/lib/python3.9/site-packages (from pydynaa<1.0,>=0.3->-r requirements.txt (line 4)) (1.11.2)
Requirement already satisfied: pandas>=0.25 in /home/anton/.local/lib/python3.9/site-packages (from netsquid<2.0.0,>=1.0.6->-r requirements.txt (line 5)) (1.3.5)
Requirement already satisfied: netsquid-physlayer<5.0.0,>=4.0.0 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from netsquid-magic<13.0.0,>=12.1.0->-r requirements.txt (line 6)) (4.3.0)
Requirement already satisfied: dataclasses<1.0.0,>=0.0.0 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from netsquid-nv<9.0.0,>=8.0.0->-r requirements.txt (line 7)) (0.6)
Requirement already satisfied: netsquid-simulationtools<3.0.0,>=2.0.0 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from netsquid-nv<9.0.0,>=8.0.0->-r requirements.txt (line 7)) (2.0.0)
Requirement already satisfied: platformdirs>=2 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from black>=20.8b1->netqasm>=0.7.0->-r requirements.txt (line 3)) (2.4.1)
Requirement already satisfied: tomli<2.0.0,>=0.2.6 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from black>=20.8b1->netqasm>=0.7.0->-r requirements.txt (line 3)) (1.2.3)
Requirement already satisfied: pathspec<1,>=0.9.0 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from black>=20.8b1->netqasm>=0.7.0->-r requirements.txt (line 3)) (0.9.0)
Requirement already satisfied: pyflakes<2.5.0,>=2.4.0 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from flake8>=3.8.3->netqasm>=0.7.0->-r requirements.txt (line 3)) (2.4.0)
Requirement already satisfied: pycodestyle<2.9.0,>=2.8.0 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from flake8>=3.8.3->netqasm>=0.7.0->-r requirements.txt (line 3)) (2.8.0)
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from flake8>=3.8.3->netqasm>=0.7.0->-r requirements.txt (line 3)) (0.6.1)
Requirement already satisfied: matplotlib>=3.2.0 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from netsquid-simulationtools<3.0.0,>=2.0.0->netsquid-nv<9.0.0,>=8.0.0->-r requirements.txt (line 7)) (3.5.1)
Requirement already satisfied: pillow>=6.2.0 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from matplotlib>=3.2.0->netsquid-simulationtools<3.0.0,>=2.0.0->netsquid-nv<9.0.0,>=8.0.0->-r requirements.txt (line 7)) (9.0.0)
Requirement already satisfied: cycler>=0.10 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from matplotlib>=3.2.0->netsquid-simulationtools<3.0.0,>=2.0.0->netsquid-nv<9.0.0,>=8.0.0->-r requirements.txt (line 7)) (0.11.0)
Requirement already satisfied: pyparsing>=2.2.1 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from matplotlib>=3.2.0->netsquid-simulationtools<3.0.0,>=2.0.0->netsquid-nv<9.0.0,>=8.0.0->-r requirements.txt (line 7)) (3.0.6)
Requirement already satisfied: python-dateutil>=2.7 in /home/anton/.local/lib/python3.9/site-packages (from matplotlib>=3.2.0->netsquid-simulationtools<3.0.0,>=2.0.0->netsquid-nv<9.0.0,>=8.0.0->-r requirements.txt (line 7)) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from matplotlib>=3.2.0->netsquid-simulationtools<3.0.0,>=2.0.0->netsquid-nv<9.0.0,>=8.0.0->-r requirements.txt (line 7)) (1.3.2)
Requirement already satisfied: packaging>=20.0 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from matplotlib>=3.2.0->netsquid-simulationtools<3.0.0,>=2.0.0->netsquid-nv<9.0.0,>=8.0.0->-r requirements.txt (line 7)) (21.3)
Requirement already satisfied: fonttools>=4.22.0 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from matplotlib>=3.2.0->netsquid-simulationtools<3.0.0,>=2.0.0->netsquid-nv<9.0.0,>=8.0.0->-r requirements.txt (line 7)) (4.28.5)
Requirement already satisfied: pytz>=2017.3 in /home/anton/.local/lib/python3.9/site-packages (from pandas>=0.25->netsquid<2.0.0,>=1.0.6->-r requirements.txt (line 5)) (2021.3)
Requirement already satisfied: six>=1.5 in /home/anton/.local/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib>=3.2.0->netsquid-simulationtools<3.0.0,>=2.0.0->netsquid-nv<9.0.0,>=8.0.0->-r requirements.txt (line 7)) (1.16.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from requests>=2.25->netqasm>=0.7.0->-r requirements.txt (line 3)) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from requests>=2.25->netqasm>=0.7.0->-r requirements.txt (line 3)) (2.0.10)
Requirement already satisfied: idna<4,>=2.5 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from requests>=2.25->netqasm>=0.7.0->-r requirements.txt (line 3)) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from requests>=2.25->netqasm>=0.7.0->-r requirements.txt (line 3)) (1.26.8)
Requirement already satisfied: Cython>=0.28 in /home/anton/.local/lib/python3.9/site-packages (from cysignals->pydynaa<1.0,>=0.3->-r requirements.txt (line 4)) (0.29.26)
Requirement already satisfied: pluggy<2.0,>=0.12 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from pytest->netqasm>=0.7.0->-r requirements.txt (line 3)) (1.0.0)
Requirement already satisfied: iniconfig in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from pytest->netqasm>=0.7.0->-r requirements.txt (line 3)) (1.1.1)
Requirement already satisfied: py>=1.8.2 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from pytest->netqasm>=0.7.0->-r requirements.txt (line 3)) (1.11.0)
Requirement already satisfied: toml in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from pytest->netqasm>=0.7.0->-r requirements.txt (line 3)) (0.10.2)
Requirement already satisfied: attrs>=19.2.0 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from pytest->netqasm>=0.7.0->-r requirements.txt (line 3)) (21.4.0)
Requirement already satisfied: coverage[toml]>=5.2.1 in /home/anton/anaconda3/envs/QComm0/lib/python3.9/site-packages (from pytest-cov->netqasm>=0.7.0->-r requirements.txt (line 3)) (6.2)
Running black...
All done! ✨ 🍰 ✨
79 files would be left unchanged.
Running flake8...
0
============================= test session starts ==============================
platform linux -- Python 3.9.7, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/anton/MsC/QCC/project/squidasm-0.8.3, configfile: pyproject.toml
plugins: cov-3.0.0
collected 51 items                                                             

tests/test_executor.py .                                                 [  1%]
tests/test_ns_util.py ....................                               [ 41%]
tests/test_qnodeos.py .                                                  [ 43%]
tests/test_run.py .                                                      [ 45%]
tests/stack/test_components.py ..                                        [ 49%]
tests/stack/test_handler.py .                                            [ 50%]
tests/stack/test_processor.py ...........                                [ 72%]
tests/stack/test_sdk.py ....                                             [ 80%]
tests/stack/test_single_node.py .....                                    [ 90%]
tests/stack/test_two_nodes.py .....                                      [100%]

----------- coverage: platform linux, python 3.9.7-final-0 -----------
Name                                        Stmts   Miss  Cover
---------------------------------------------------------------
squidasm/__init__.py                            1      0   100%
squidasm/nqasm/__init__.py                      0      0   100%
squidasm/nqasm/executor/__init__.py             0      0   100%
squidasm/nqasm/executor/base.py               122     31    75%
squidasm/nqasm/executor/nv.py                  28     13    54%
squidasm/nqasm/executor/vanilla.py             13      0   100%
squidasm/nqasm/multithread.py                  57     11    81%
squidasm/nqasm/netstack.py                     77      3    96%
squidasm/nqasm/output.py                       41     15    63%
squidasm/nqasm/qnodeos.py                     167     10    94%
squidasm/nqasm/singlethread/__init__.py         0      0   100%
squidasm/nqasm/singlethread/connection.py      71     71     0%
squidasm/nqasm/singlethread/csocket.py         20     20     0%
squidasm/run/__init__.py                        0      0   100%
squidasm/run/multithread/__init__.py            0      0   100%
squidasm/run/multithread/runtime_mgr.py       163     10    94%
squidasm/run/multithread/simulate.py           61     46    25%
squidasm/run/singlethread/__init__.py           2      2     0%
squidasm/run/singlethread/context.py           43     43     0%
squidasm/run/singlethread/protocols.py        168    168     0%
squidasm/run/singlethread/run.py               72     72     0%
squidasm/run/singlethread/util.py              40     40     0%
squidasm/run/stack/__init__.py                  0      0   100%
squidasm/run/stack/build.py                    49     14    71%
squidasm/run/stack/config.py                  121     17    86%
squidasm/run/stack/run.py                      85     85     0%
squidasm/sim/__init__.py                        0      0   100%
squidasm/sim/glob.py                           98     34    65%
squidasm/sim/network/__init__.py                2      0   100%
squidasm/sim/network/network.py               243     56    77%
squidasm/sim/network/nv_config.py              72     34    53%
squidasm/sim/queues.py                         51      6    88%
squidasm/sim/stack/__init__.py                  0      0   100%
squidasm/sim/stack/common.py                  258     28    89%
squidasm/sim/stack/connection.py               51      6    88%
squidasm/sim/stack/context.py                  43      8    81%
squidasm/sim/stack/csocket.py                  30     10    67%
squidasm/sim/stack/egp.py                      69     14    80%
squidasm/sim/stack/globals.py                  40     21    48%
squidasm/sim/stack/handler.py                 166     12    93%
squidasm/sim/stack/host.py                     98      7    93%
squidasm/sim/stack/netstack.py                290     48    83%
squidasm/sim/stack/processor.py               505    144    71%
squidasm/sim/stack/program.py                  37      3    92%
squidasm/sim/stack/qnos.py                    118      5    96%
squidasm/sim/stack/sdk.py                      67     67     0%
squidasm/sim/stack/signals.py                   8      0   100%
squidasm/sim/stack/stack.py                   117      8    93%
squidasm/util/__init__.py                       0      0   100%
squidasm/util/ns.py                            43      3    93%
squidasm/util/sim.py                           28      5    82%
squidasm/util/thread.py                        15      2    87%
---------------------------------------------------------------
TOTAL                                        3850   1192    69%


============================= 51 passed in 24.46s ==============================
Running example /home/anton/MsC/QCC/project/squidasm-0.8.3/examples/singlethread/bqc/run.py
Running example /home/anton/MsC/QCC/project/squidasm-0.8.3/examples/raw_subroutines/example_bqc_subrt.py
Running example /home/anton/MsC/QCC/project/squidasm-0.8.3/examples/raw_subroutines/example_ll_subrt.py
Running example /home/anton/MsC/QCC/project/squidasm-0.8.3/examples/stack/link_layer_custom_subrt/example_ll_custom_subrt.py
Traceback (most recent call last):
  File "/home/anton/MsC/QCC/project/squidasm-0.8.3/examples/stack/link_layer_custom_subrt/example_ll_custom_subrt.py", line 22, in <module>
    with open(client_subrt_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/anton/MsC/QCC/project/squidasm-0.8.3/examples/stack/link_layer_custom_subrt/client.nqasm'
Traceback (most recent call last):
  File "/home/anton/MsC/QCC/project/squidasm-0.8.3/examples/run_examples.py", line 36, in <module>
    main()
  File "/home/anton/MsC/QCC/project/squidasm-0.8.3/examples/run_examples.py", line 30, in main
    raise RuntimeError(f"Example {filepath} failed!")
RuntimeError: Example /home/anton/MsC/QCC/project/squidasm-0.8.3/examples/stack/link_layer_custom_subrt/example_ll_custom_subrt.py failed!
make: *** [Makefile:67: examples] Error 1
```

And the file `examples/stack/link_layer_custom_subrt/example_ll_custom_subrt.py` does exist in my local folder.

**Comment by bvdvecht** [comment]
I see now that the `FileNotFoundError` is about `client.nqasm`. Does that file exist in the `link_layer_custom_subrt` directory? If it does, I have no idea why it would not be able to find it when running the example...

**Comment by ARO-GZ** [comment]
No, in that file there is only the `example_ll_custom_subrt.py` file.

**Comment by bvdvecht** [comment]
As you can see here https://github.com/QuTech-Delft/squidasm/tree/develop/examples/stack/link_layer_custom_subrt there is supposed to be a `client.nqasm` file. Maybe try a clean `git clone` and see if you end up with that file?

**Comment by ARO-GZ** [comment]
That made the job! It seems to be working now. Thanks a lot!!

(It might be worth mentioning that I obtained the incomplete repository from https://pypi.org/project/squidasm/ ,which is the first entry when googling squidasm. You may be able to fix the problem there for those interested in the future)

**Comment by bvdvecht** [comment]
Glad to hear that solved it!

Thanks for the info regarding the source code on PyPI. We'll look into fixing that.
